version: '3.9'
services:
  db:
    image: mongo:6.0.4
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongodb_data_container:/data/db
    expose:
      - 27017

  backend:
    container_name: ppromat-be
    build:
      context: backend
      dockerfile: Dockerfile
    image: ppromat-be:latest
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://db:27017/PproDbs
      - SERVER_PORT=8080


  frontend:
    container_name: ppromat-fe
    build:
      context: frontend
      dockerfile: Dockerfile
    image: ppromat-fe:latest
    ports:
      - "3000:3000"


volumes:
  mongodb_data_container: